name: healery
description: A social media app related to mental health


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.3
  google_sign_in: ^5.0.1
  firebase_core: ^1.0.2

  provider: ^4.3.3
  paginate_firestore: ^0.3.1
  flutter_snake_navigationbar: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true


  assets:
    - assets/images/

  fonts:
  - family: Syne
    fonts:
    - asset: assets/fonts/SyneMono-Regular.ttf

  - family: Nunito
    fonts:
    - asset: assets/fonts/Nunito-Black.ttf

  - family: Balsamiq
    fonts:
    - asset: assets/fonts/BalsamiqSans-Regular.ttf

  - family: Dancing
    fonts:
    - asset: assets/fonts/Dancing.ttf
